orm_store_app/urls.py
from django.contrib import admin
from django.urls import path
from .import views

app_name = 'orm_store_app'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    # path('datetime_nov/', views.datetime_nov, name='datetime_nov'),
    # path('list_dict/', views.list_dict, name='list_dict'),
    # path('form_create_0/', views.form_create_0, name='form_create_0'),
    # path('form_create/', views.form_create, name='form_create'),
    # path('form_result/', views.form_result, name='form_result'),
    # path("store_result/", views.store_result, name="websiteApp-store_result"),
    path('category/', views.category, name='category'),
    path('table/<int:pk>', views.table, name='table'),
    path('page/<int:pk>', views.page, name='page'),
    path('store_result', views.store_result, name='store_result'),
    # path("store/", views.store),

]

orm_store_prj/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('orm_store_app.urls')),
]

orm_store_app/models.py
# import datetime
from django.db import models


class Category(models.Model):
    name = models.CharField('Категория', max_length=255)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ('id',)

    def __str__(self):
        return self.name


class Item(models.Model):
    category = models.ForeignKey(Category, related_name='Категория',  on_delete=models.CASCADE)
    name = models.CharField('Товар', max_length=255)
    description = models.TextField('Описание', blank=True, null=True)
    price = models.FloatField('Цена', )
    vendor_code = models.IntegerField('Артикул',  blank=False , null=False)
    image = models.ImageField(upload_to='orm_store_app/static/item_images', blank=True, null=True)
    is_sold = models.BooleanField('Проданы', default=False)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ('name',)

    def __str__(self):
        return '%s %s' % (self.category, self.name)
        # return self.name

# current_date = models.DateTimeField("ДатаВремя", default=datetime.datetime.now())
# current_date = models.DateTimeField("ДатаВремя", auto_now_add=True)


# python manage.py makemigrations
# python manage.py migrate


# admin.py
# from django.contrib import admin
# # Register your models here.
# from .models import Abc
# admin.site.register(Abc)


# forms.py
# from django.forms import ModelForm
# from .models import Abc
#
# class CreateAbcForm(ModelForm):
#     class Meta:
#         model = Abc
#         fields = ['task', 'a' ,'b' ,'c', 'c_calc']


# c_choices = (
#     (0, "ноль"),
#     (10, "десять"),
#     (15, "пятнадцать"),
#     (20, "двадцать"),
# )
#
#
# class Store(models.Model):
#     task = models.CharField("Формулировка задачи", default="Равна ли С сумме A и B ?", max_length=256)
#     a = models.IntegerField("Значение А", default=0, )
#     b = models.IntegerField("Значение B", default=0, help_text="Подсказка для поля")
#     c = models.IntegerField("Значение С", choices=c_choices, default=0, )
#     current_date = models.DateTimeField("Дата Записи", auto_now=True)
#
#     def __str__(self):
#         # return self.task
#         return '%s %s' % (self.task, self.current_date)
#
#     class Meta:
#         verbose_name = "A_B_C"
#         verbose_name_plural = "A_B_C_S"
#         # ordering = ("-c", "b")

orm_store_app/views.py
from django.shortcuts import HttpResponse,render, redirect
from . models import Category, Item
# from . forms import CreateAbcForm

import datetime
from django.db.models.fields import (
    DateField, DateTimeField, DurationField, Field, IntegerField, TimeField,
)

def index(request):
    return render(request, 'index.html')


def table(request, pk):
    print("pk: ", pk)
    objects_list = Item.objects.filter(category_id__gt=pk).values().order_by('-category_id')
    print('objects_list: ', objects_list)
    context = {'objects_list': objects_list}
    return render(request, 'table.html', context)

def category(request):
    # from orm_store_app.models import Category, Item
    objects = Category.objects.all().values()
    print("objects:\n", list(objects))
    context={'objects_list': list(objects)}
    return render(request, 'category.html', context)

def page(request, pk):
    # from orm_store_app.models import  Category, Item
    category = Category.objects.values()
    print("category:\n", category)
    # category = {'category': category}

    items = Item.objects.values().filter(category=pk)
    print("\nitems:\n", items)
    for item in items:
        print('\nitem: ', item)
        lst= list((item['image'].split('/'))[-2:])
        img_value = (lst[0] + '/' + lst[1])
        print ('img_value: ', img_value)
        item['image'] = img_value
    print("items:\n", items)
    # items = {'items': items}
    context = {"category": category, "items": items  }
    return render(request, 'page.html', context)


def store_result(request):
    print(request.GET)
    return HttpResponse(f"""
    """)

orm_store_app/templates/index.html
{% extends 'layout.html' %}

{% block title %}
    orm_abc_app:index-title
{% endblock %}

{% block content %}
    <h5>orm_abc_app:index-content</h5>
{% endblock %}

orm_store_app/templates/layout.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    {% load static %}
    <link href="{% static 'css/mycss.css' %}" rel="stylesheet">
    <title>{% block title %}{% endblock %}</title>
</head>

<div class="container">

    <div class="card">
        <div class="card-body bgc">
            {% load static %} <img src="{% static 'images/settings_django.png' %}"
                                   alt="settings_django" height="30px">
            <p>object-relational mapper
            </p>
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            {% include "navigation.html" %}
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            {% block content %}{% endblock %}
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            Footer
        </div>
    </div>

</div>

<body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>
</html>

orm_store_app/templates/navigation.html
<ul class="nav">
    <li class="nav-item"><a class="nav-link" href="{% url 'orm_store_app:index' %}">index</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'orm_store_app:table' pk=1 %}">table</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'orm_store_app:page' pk=4 %}">page</a></li>
</ul>

orm_store_app/templates/old/category.html
{% extends 'layout.html' %}

{% block title %}orm_abc_app:list{% endblock %}

{% block content %}
    <h5>contant_main_list_dict</h5>
    <p>category
{#        <br>{{ object_list }}#}
        {% for object in objects_list %}
            <br>{{ object.id }}: {{ object.name }}
            <li><a href="{%  url 'orm_store_app:table' pk=object.id %}">{{ object.name }}</a></li>
        {% endfor %}
    </p>
{% endblock %}

orm_store_app/templates/old/datetime_now.html
{% extends 'layout.html' %}

{% block title %}
    orm_abc_app: date_time
{% endblock %}

{% block content %}
    <h5>orm_abc_app:date_time-content</h5>
    datetime_now: {{ key }}
{% endblock %}

orm_store_app/templates/old/form_create.html
{% extends 'layout.html' %}

{% block title %} form_abc_app:form_create {% endblock %}

{% block content %}
    <h5>orm_abc_app:form_create</h5>
    {% load widget_tweaks %}
    <form method="POST">
        {% csrf_token %}
        <div class="form-group mb-1">
            <div class="mb-1 row">
                <label class="col-sm-2 col-form-label">Формулировка</label>
                <div class="col-sm-10">
                    {% render_field form.task class="form-control" %}
                </div>
            </div>

            <div class="mb-1 row">
                <label class="col-sm-2 col-form-label">A</label>
                <div class="col-sm-10">
                    {% render_field form.a class="form-control" %}
                </div>
            </div>

            <div class="mb-1 row">
                <label class="col-sm-2 col-form-label">B</label>
                <div class="col-sm-10">
                    {% render_field form.b class="form-control" %}
                </div>
            </div>

            <div class="mb-1 row">
                <label class="col-sm-2 col-form-label">C</label>
                <div class="col-sm-10">
                    {% render_field form.c class="form-control" %}
                </div>
            </div>


            <div class="mb-1 row">
                <label class="col-sm-8 col-form-label"></label>
                <div class="col-sm-4 text-end">
                    <button type="submit" class="form-control">Отправить</button>
                </div>
            </div>
        </div>

    </form>
{% endblock %}

orm_store_app/templates/old/form_create_0.html
{% extends 'layout.html' %}

{% block title %} form_abc_app/form_create_0 {% endblock %}

{% block content %}
    <h5>orm_abc_app:form_create_0</h5>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <label for="id_submit">&nbsp;</label>
        <button type="submit" id="id_submit">Отправить</button>
        </label>
    </form>
{% endblock %}

orm_store_app/templates/old/form_result.html
{% extends 'layout.html' %}

{% block title %}orm_abc_app:result{% endblock %}

{% block content %}
    <h5>orm_abc_app:result</h5>
    <h6>
        {% for item in task_main %}
            {{ item }}
        {% endfor %}
    </h6>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th scope="col">A</th>
            <th scope="col">B</th>
            <th scope="col">C</th>
            <th scope="col">Результат</th>
        </tr>
        </thead>
        <tbody style="border-top: 0px;">
        <tr>
            {% for item in last_data %}
                <td>
                    {{ item }}
                </td>
            {% endfor %}
        </tr>
        </tbody>
    </table>
{% endblock %}

orm_store_app/templates/old/list_main.html
{% extends 'layout.html' %}

{% block title %}orm_abc_app:list{% endblock %}


{% block content %}
    <h5>contant_main_list_dict</h5>
    <p>list_main
        <br>{{ list_main }}
        <br>{{ list_main.2}}
        {% for value in list_main %}
            <br>{{ value }}
        {% endfor %}
    </p>
    <p>dict_main
        <br>{{ dict_main }}
        <br>{{ dict_main.x }}
        <br>{{ dict_main.y }}
        {% for key, value in dict_main.items %}
            <br>{{ key }}: {{ value }}
        {% endfor %}
    </p>
{% endblock %}

orm_store_app/templates/old/store.html
{% extends "../websiteApp/layout.html" %}


{% block title %}
    <title>Store</title>
{% endblock %}


{% block main %}
    {% load static %}
    <div id="pk" name={{ urls.last_url_element }}>{{ urls.last_url_element }}</div>
    <h5 class="card-title text-center">Магазин</h5>
    {#    path_element: {{path_element.path_element}}#}
    {#    <br>objects_array: {{objects_array.objects_array}}#}

    <div class="card">
        <div class="card-body">
{#            <form action="https://www.bing.com/search" id="UserEnter" name="UserEnter" target="_blank">#}
            <form action="{% url 'websiteApp:websiteApp-store_result' %}" id="UserEnter" name="UserEnter" target="_blank">
                <ul class="d-flex flex-row flex-wrap ">
                    {% for object in dict_of_array.objects_array %}
                        <li class="m-2 list-group-item bg-light border p-3">
                            <img src="{% static object.img %}" width="200px>">
                            <img src="{{ object.img }}" width="200px>">
                            <h6>{{ object.title }}</h6>
                            <p>{{ object.description }}. Цена: {{ object.price }}р.
                                <input name="vendor_code" type="hidden" value={{ object.vendor_code }}>
                                <br>Заказать<input style=" width: 2.0rem;" name="amount" type="text" value=0> шт.
                            </p>
                        </li>
                    {% endfor %}
                </ul>
                <button class="btn btn-primary" type="submit">Отправить</button>
            </form>
        </div>
    </div>

{% endblock %}





{% comment %}
<ul>
    {% for object in objects_array %}
        <li>
            {% for key, value in object.items %}
                {{ key }}: {{ value }}
                {{ value }}
            {% endfor %}
        </li>
    {% endfor %}
</ul>
{% endcomment %}


{% comment %}

        <li class="m-2 list-group-item">
        <img src=${content[key].img} width="200px">
        <h6>${content[key].title}</h6>
        <p>${content[key].description}. Цена
        ${content[key].price} р.</p>
        <p>Заказать
        <input type="hidden" name= "vendor_code" value=${content[key].vendor_code}>
        <input type="number" name="amount" value="0" style="width: 2.0rem;">
        </p>
        </li>

{% endcomment %}


</body>
</html>

orm_store_app/templates/old/store_result.html
{% extends "../websiteApp/layout.html" %}


{% block title %}
    <title>Store</title>
{% endblock %}


{% block main %}
    {% load static %}
    <div id="pk" name={{ urls.last_url_element }}>{{ urls.last_url_element }}</div>
    <h5 class="card-title text-center">Магазин Результаты</h5>
    {#    path_element: {{path_element.path_element}}#}
    {#    <br>objects_array: {{objects_array.objects_array}}#}

    <div class="card">
        <div class="card-body">
            {{ d }}
        </div>
    </div>

{% endblock %}



{% comment %}
<ul>
    {% for object in objects_array %}
        <li>
            {% for key, value in object.items %}
                {{ key }}: {{ value }}
                {{ value }}
            {% endfor %}
        </li>
    {% endfor %}
</ul>
{% endcomment %}


{% comment %}

        <li class="m-2 list-group-item">
        <img src=${content[key].img} width="200px">
        <h6>${content[key].title}</h6>
        <p>${content[key].description}. Цена
        ${content[key].price} р.</p>
        <p>Заказать
        <input type="hidden" name= "vendor_code" value=${content[key].vendor_code}>
        <input type="number" name="amount" value="0" style="width: 2.0rem;">
        </p>
        </li>

{% endcomment %}


</body>
</html>

orm_store_app/templates/page.html
{% extends 'layout.html' %}

{% block title %}orm_store_page{% endblock %}

{% block content %}
    <h6>Category</h6>
{#    <p>category: {{ category }}</p>#}
    <ul>
        {% for object in category %}
            <li>
{#                {{ object.id }}: {{ object.name }}#}
                <a href="{% url 'orm_store_app:page' pk=object.id %}">{{ object.name }}</a>
            </li>
        {% endfor %}
    </ul>

    {% load static %}
     <div class="card">
        <div class="card-body">
            {#            <form action="https://www.bing.com/search" id="UserEnter" name="UserEnter" target="_blank">#}
            <form action="{% url 'orm_store_app:store_result' %}" id="UserEnter" name="UserEnter" target="_self">
                <ul class="d-flex flex-row flex-wrap ">
                    {% for item in items %}
                        <li class="m-2 list-group-item bg-light border p-3">
                            <img src="{% static item.image %}" width="200px>">
                            <h6>{{ item.name }}</h6>
                            <p>{{ item.description }}. Цена: {{ item.price }}р.
                                <input name="vendor_code" type="hidden" value={{ item.vendor_code }}>
                                <br>Заказать<input style=" width: 2.0rem;" name="amount" type="text" value=0> шт.
                            </p>
                        </li>
                    {% endfor %}
                </ul>
                <button class="btn btn-primary" type="submit">Отправить</button>
            </form>
        </div>
    </div>
{% endblock %}

orm_store_app/templates/table.html
{% extends 'layout.html' %}

{% block title %}orm_store_table:table{% endblock %}


{% block content %}
    <h5>orm_store_table</h5>
    <table class="table table-bordered">
        <tbody style="border-top: 3.0px;">
{#        <p>objects_list: {{ objects_list }}</p>#}
        {% for object in objects_list %}
{#            <br>object: {{ object }}#}
            <tr>
                {% for key, value in object.items %}
                    <td>
                        {{ value }}
                    </td>
                {% endfor %}

            </tr>
        {% endfor %}
        <tbody>
    </table>
{% endblock %}